# Site settings
title: spark
email: 3241651990@qq.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spark927.github.io" # the base hostname & protocol for your site
twitter_username: spark
github_username:  spark927

# Build settings
rouge: pygments
markdown: kramdown
kramdown:
    input: GFM
    
paginate: 5
paginate_path: "page:num"

plugins: [jekyll-paginate]
